### ISSUE TITLE
フォルダ監視機能

### ISSUE THREAD

**Issue by PEkyokutyo** [3846masa/upload-gphotos#106]
MP4のバックアップにGoogle photoを使っているのですが、一つ一つ列挙していくのも面倒ですし、今のところGoogle photoの公式もlinux版を出すような気配はしないので、需要はあると考えられます。なので特定フォルダを自動アップロードするオプション(差分でアップロード)を追加出来ないでしょうか。

**Comment by 3846masa** [comment]
提案ありがとうございます．

わたし個人としては，今のところフォルダ監視機能については必要としていないため，わたしが実装することは恐らくありません．
upload-ghotos はライブラリとしても機能しますので，そちらを使って実装していただけると幸いです．

機能追加の Pull Request については歓迎しています．
もし，実装後に upload-gphotos へ統合したい場合は別途 PR を送ってください．

**Comment by PEkyokutyo** [comment]
了解です。
