### ISSUE TITLE
[Feature] if i upload a video return the rawURL for a video

### ISSUE THREAD

**Issue by zodman** [3846masa/upload-gphotos#128]
thanks for it

**Comment by 3846masa** [comment]
Sorry, I can't understand what you say. My English skill is poor.
So, please write more about your problem.
Here is Issues form, so If you have no issues, please close this.

**Comment by 3846masa** [comment]
Temporarily, I'll close it.
If you have issues, please write more details again.

**Comment by zodman** [comment]
to clarify im using upload-gphotos to upload a video. I need the video direct mp4 url for embed on html5 code. ( free video hosting on google photos).

I test and check the response gphoto rest calls on browser and that info dont comes with it.

But i can getting it with de meta property="og:video" on the direct  share url.

Then the issue its invalid because its not related to the upload-gphotos. closed!

**Comment by kristoff2016** [comment]
Hello @zodman could you share me your code how you do upload mp4 or mp3 to google ?
