### ISSUE TITLE
Server Error: sessionStatus is not found.

### ISSUE THREAD

**Issue by hklcf** [3846masa/upload-gphotos#130]
![image](https://cloud.githubusercontent.com/assets/410302/22561382/ef27a8a2-e9b2-11e6-8251-3fe9e95c59d7.png)

**Comment by 3846masa** [comment]
@hklcf Please write more details.

- Can you login to Google with machine that running upload-gphotos
- What's image you sent
  - Can you upload via Google Photos on Web
- What's params passed to upload-gphotos

And binary is not recommended, Please try npm package.

**Comment by 3846masa** [comment]
I'll close this issue temporally.
If you haven't resolved this issue yet, please resend your issue with more details.
