### ISSUE TITLE
Upload speed.

### ISSUE THREAD

**Issue by nexushp** [3846masa/upload-gphotos#149]
Hi! Very nice uploader, but how I can increase the upload speed? I'm using on my server and it's uploading at 10mb/s but my server can upload up to 50mb/s.

PS: When I upload via Google Chrome (photos.google.com) I reach at 18, 20mb/s of speed.
Thanks in advance, 

Screenshot: http://prntscr.com/eeikpa

**Comment by 3846masa** [comment]
Sorry, I have no clear solution for your issue.

But, I think progress bar might cause slow uploading.
https://github.com/3846masa/upload-gphotos/blob/10cc1bc661dc9f46789830990a77ec1b296a9de9/src/index.js#L414-L426

Please try to disable progressbar.
