### ISSUE TITLE
Upload-Gphotos won't upload files

### ISSUE THREAD

**Issue by greg5678** [3846masa/upload-gphotos#166]
I ran the command `upload-gphotos -u usernamegoeshere -p passwordgoeshere file example.jpg` (I changed the username and password along with a file in the same directory that the command was ran in. The program didn't do anything for about two seconds and then the help section came up. FYI I allowed less secure apps. I checked google photos and the google drive but the file was not there.

**Comment by 3846masa** [comment]
Sorry for the late reply.
I think your command is mistaken.

If you want to upload `example.jpg`, you should type `upload-gphotos -u USERNAME -p PASSWORD example.jpg` or `upload-gphotos example.jpg` (Interactive).

**Comment by 3846masa** [comment]
I'll close.
If you have problems yet, please resend issue.
