### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by nm7** [3846masa/upload-gphotos#2]
Ubuntu 15.10 にて実行したところ、以下のようなエラーでアップロードできませんでした。
API の仕様が変わってしまったのでしょうか…？

Success to login!
UserID is ?authuser=0.

Uploading [==========================================================================================================================================================================================] 100% 0.0s

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at nexe.js:370:23
    at next (native)
    at onFulfilled (nexe.js:36693:19)
    at process._tickCallback (node.js:361:9)

**Comment by 3846masa** [comment]
ログイン処理がうまく行っていないのだと思います．
upload-gphotosを使うには，Googleアカウントで一度Google+の設定をする必要があります．
確認してみてください．

**Comment by nm7** [comment]
Google+のアカウント設定を行うことにより、正常にアップロードできました。ありがとうございます！
