### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by 4getit** [3846masa/upload-gphotos#201]
Hi,

Finally a working cli! I had some trouble with the Google Authentication verification on my VPS but I was able to get through by using a text based browser.

I have a few feature requests. Hopefully you'll find them useful :)

- An option to list all files (json?). Either all or a specific folder. With Google ID's, filename, upload datetime etc..

- An option to delete a remote file (via ID?)

- An option to remove the local file after the upload is confirmed successful.

Thank you very much for your tool. It's a lifesaver for me.

**Comment by 3846masa** [comment]
I have no plan to add new feature at the moment.
However, `upload-gphotos` in npm is also Node.js library.
You can write code that works you want to.
Please see [document](https://doc.esdoc.org/github.com/3846masa/upload-gphotos/) for more details.

- List all files
```js
const GPhotos = require('upload-gphotos');
const gphotos = new GPhotos({
  username: 'username@gmail.com',
  password: 'YOUR_PASSWORD',
});

gphotos.login()
.then(() => gphotos.fetchAllPhotoList())
.then((list) => console.log(JSON.stringify(list, null, 2)));
```

- Delete file
```js
const GPhotos = require('upload-gphotos');
const gphotos = new GPhotos({
  username: 'username@gmail.com',
  password: 'YOUR_PASSWORD',
});

gphotos.login()
.then(() => gphotos.fetchPhotoById('PHOTOS_ID'))
.then((photo) => photo.remove());
```

- Remove local file after uploading
```sh
# Shell script is easy way.
$ upload-gphotos ./picture.png && rm ./picture.png
```

**Comment by 4getit** [comment]
Nice. Thank you!
