### ISSUE TITLE
Feature Request: Support Multiple Albums

### ISSUE THREAD

**Issue by neocryptek** [3846masa/upload-gphotos#207]
Hi,

It would be nice if one could specify the -a album parameter multiple times to put an upload into multiple albums. Right now if you try that it seems to concatenate the two album names together with a comma, and then a bad request error is returned from the server.

Seems like it might be an easy fix to loop through them instead of if once here:
https://github.com/3846masa/upload-gphotos/blob/master/src/cli.js#L59

**Comment by 3846masa** [comment]
Sorry for the late reply.
Fixed on v1.4.3.

**Comment by neocryptek** [comment]
Thanks!

What's the syntax to get the CLI to recognize the multiple album names? The help message doesn't seem to have changed.

I see you have the argument set as an array which according to yargs means we should do -a Album1 Album2 or maybe -a Album1 -a Album2
https://github.com/3846masa/upload-gphotos/blob/109073878e1c71f7b5c3358f74a2de46f913fca0/src/cli.js#L37-L41
https://github.com/yargs/yargs/blob/master/docs/tricks.md#arrays

But that seems to concatenate them together with a comma and it tries to create the single album "Album1,Album2" which Google Photos then rejects as an invalid album name.

upload-gphotos -u user -p pass file1 file2 -a Album1 Album2 

```
Usage: upload-gphotos [-u username] [-p password] [-a albumname] file [...]
...help text as cli thinks this is invalid args...
```

upload-gphotos -u user -p pass file1 file2 -a Album1 -a Album2

```
INFO Uploaded successfully!
ERROR Album "Album1,Album2" is not found.
ERROR Failed to create album. Bad Request
ERROR Error: Bad Request
    at /usr/local/lib/node_modules/upload-gphotos/lib/index.js:477:31
```


I tried using -- to separate out album names an file names, since -a is marked as an array
https://github.com/yargs/yargs/blob/master/docs/tricks.md#stop-parsing

upload-gphotos -u user -p pass -a Album1 -a Album2 -- file1 file2

```
INFO Uploaded successfully!
ERROR Album "Album1,Album2" is not found.
ERROR Failed to create album. Bad Request
ERROR Error: Bad Request
    at /usr/local/lib/node_modules/upload-gphotos/lib/index.js:477:31
```

upload-gphotos -u user -p pass -a Album1 Album2 -- file1 file2

```
Usage: upload-gphotos [-u username] [-p password] [-a albumname] file [...]
...help text as cli thinks this is invalid args...
```

**Comment by 3846masa** [comment]
I think you executed old version.
Using latest version, it shows below as help.

```
$ upload-gphotos --help
Usage: upload-gphotos file [...] [-u username] [-p password] [-a albumname]

Options:
  -u, --username  Google account username.
  -p, --password  Google account password.
  -a, --album     Album where uploaded files put.                        [array]
  -h, --help      Show help                                            [boolean]
```

Please try to remove upload-gphotos before reinstall.

**Comment by neocryptek** [comment]
Looks like that was the problem, npm had different versions in /usr, /usr/local, and my home directory than what it was listing as installed and the old version was indeed on the PATH first.

Could you add the version number to the help output (or a --version arg) to make this easier to troubleshoot what version is actually being used?

Thanks!

**Comment by 3846masa** [comment]
> Could you add the version number to the help output (or a --version arg) to make this easier to troubleshoot what version is actually being used?

I agree, I'll make it.
