### ISSUE TITLE
Make share photo after upload

### ISSUE THREAD

**Issue by tranvu711** [3846masa/upload-gphotos#209]
Hi there,

As title, how to make share public photo with photoID after upload? 

Thanks

**Comment by 3846masa** [comment]
This library is not supported to make the share URL.
However, you can get the raw URL via `photo.rawUrl`.

```js
import GPhotos from 'upload-gphotos';
(async () => {
const gphotos = new GPhotos({
  username: 'username@gmail.com',
  password: 'YOUR_PASSWORD'
});
await gphotos.login();
const photo = await gphotos.fetchPhotoById('PHOTO_ID');
console.log(photo.rawUrl);
})();
```

**Comment by movewho** [comment]
I've read your code and understood a bit. I'm trying to write a function to create a shared link. Thanks you.

**Comment by 3846masa** [comment]
I'll close temporary.
If anyone have issue, please create new issue.
