### ISSUE TITLE
Can't fetch userID from Google+ URL.

### ISSUE THREAD

**Issue by Einstein2150** [3846masa/upload-gphotos#21]
I've got an Error after Login. The Login must be correct, because I got a Mail from Google that somebody logged into my account. I set the less-secure option before. Here is the error:
`osmc@osmc:~$ cd gphotos/
osmc@osmc:~/gphotos$ upload-gphotos -u xxxxxxxx@gmail.com -p xxxxxx IMG_0458.JPG
ERROR Failed to login...
WARN Tips: Before to login, you should setup Google+.
Error: Failed to login
    at /usr/local/lib/node_modules/upload-gphotos/lib/index.js:171:31
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/upload-gphotos/node_modules/co/index.js:65:19)
    at tryCatcher (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/util.js:16:23)    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/upload-gphotos/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
osmc@osmc:~/gphotos$
`
I'm running the latest version 1.0.4 from the npm-repository.

**Comment by 3846masa** [comment]
I think you should setup Google+.
Please access below and setup Google+.
https://plus.google.com/u/0/me

**Comment by Einstein2150** [comment]
Everything is setup in G+. I have a account there for several years. Is there a special option to set? I couldn't find anything ...

**Comment by 3846masa** [comment]
Hmm....

Which do you run at local PC or server ?
If at server, please login via browser at server.

upload-gphotos check redirects accessing to https://plus.google.com/u/0/me ( likes https://plus.google.com/u/0/111758550105837157414 ).
So, please check redirect via browser.

**Comment by Einstein2150** [comment]
It runs on a Raspberry Pi 2 with OSMC. It has a own GUI but no really X-Window-based GUI. There is no Browser which i can run on it. I only SSH into the Machine. I checked the Link on an other PC.  https://plus.google.com/u/0/me directs me to https://plus.google.com/u/0/+RaikSchneider

**Comment by 3846masa** [comment]
Oh.... upload-gphotos get number from https://plus.google.com/u/0/[number].
I'll try to get number from other source.

**Comment by Einstein2150** [comment]
OK. There was an offer a few month ago from Google to create a special individual "shortcut" which means that I'm now "+RaikSchneider" which is more comfortable than a big number :-)

**Comment by 3846masa** [comment]
Fixed.
https://github.com/3846masa/upload-gphotos/tree/fix/21

Please try it.

```sh
git clone -b fix/21 https://github.com/3846masa/upload-gphotos.git
cd upload-gphotos
npm i
npm run build:babel
node lib/cli.js -u $GOOGLE_USER -p $GOOGLE_PASS filename.jpg
```

**Comment by 3846masa** [comment]
If success, I'll merge to master.

**Comment by Einstein2150** [comment]
Thank you. I'll test it. Are there dependencies to the current installation of upload-gphotos via npm? I'm new to git and dont't understand all the way the "git clone" works.

I think that: git clone copys the bugfix-files to my machine, and with the npm-commands i test it in this separate directory. A'm I right? There are no dependencies to the installation via npm-repository or?
Sorry for the stupid question :-)

**Comment by 3846masa** [comment]
Sorry, I don't understand what you said. I cannot read/write english well.

Fixed code is not uploaded to npm yet, so when you try fixed code, you should clone fixed code.
And, my code is ES6, required to build. so, you should ``npm i && npm run build`` first.
upload-gphotos command is ``lib/cli.js``. Try to ``node lib/cli.js -u username -p password filename.jpg``.

**Comment by Einstein2150** [comment]
I have problems Doping npm i:
`osmc@osmc:~/test/upload-gphotos$ npm i
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
osmc@osmc:~/test/upload-gphotos$`

When I try to get fsevents i get
`osmc@osmc:~$ sudo npm install -g fsevents                                                                           
npm ERR! Linux 4.4.16-4-osmc
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "fsevents"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: arm

npm ERR! Please include the following file with any support request:
npm ERR!     /home/osmc/npm-debug.log`

**Comment by Einstein2150** [comment]
After that:
`osmc@osmc:~/test/upload-gphotos$ node lib/cli.js -u xxxxxxxxx@gmail.com -p xxxxxxx IMG_0458.JPG       
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/osmc/test/upload-gphotos/lib/cli.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3`

**Comment by 3846masa** [comment]
fsevents is required on OS X. You shouldn't install fsevents.
And you should ``npm run build``.

**Comment by Einstein2150** [comment]
Sorry, my mistake.

After npm install -g npm@3.3.12 I was able to install it. I run it and **it worked**!

**Comment by 3846masa** [comment]
:tada: LGTM
I'll merge and build via CI.

**Comment by 3846masa** [comment]
v1.0.5 released to npm.
You can use patched code after ``npm i -g upload-gphotos@latest``.
