### ISSUE TITLE
No way to run two command at the same time?

### ISSUE THREAD

**Issue by cnritng** [3846masa/upload-gphotos#213]
when I try to run another "upload-gphotos" command in another window,the original got killed...

**Comment by 3846masa** [comment]
Please more info.

- What's Error outputted?
- What's file you want to upload?
  - filetype (photo or video)
  - filesize
  - etc.

However, I recommend not to run parallelly.

**Comment by cnritng** [comment]
@3846masa 
filetype:video
filesize:1.5GB
MEM:1GB
I think it's probably the memery issue....

**Comment by cnritng** [comment]
memory-cause issue
