### ISSUE TITLE
Wrong created date

### ISSUE THREAD

**Issue by ManuCart** [3846masa/upload-gphotos#226]
Hi,

I don't know why but when I upload a photo the date is wrong
```
{
    "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "uploadedAt": "2017-07-11T20:52:27.771Z",
    "createdAt": "1907-01-02T04:00:00.000Z",
    "title": "1907.0005.JPG",
    "description": "",
    "rawUrl": "https://lh3.googleusercontent.com/xxxxxxxxxxxx/xxxxxxxxxxx/xxxxxxxxxxx-x/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/1907.0005.JPG",
    "type": "photo"
  }
```
and the real creation date is ```1907-01-01T04:00:00.000Z```
I have one day more than the image time stamp

**Comment by 3846masa** [comment]
Sorry, I have no idea.
`upload-gphotos` don't send metadata, do only send binary.
I think it is Google Photos' bug or your file's EXIF is invalid.
Please check below.

- Upload via browser and Check creation date.
- Check your original file's EXIF.

**Comment by ManuCart** [comment]
Hello,
Yes it's seem a Google Photos bug
Because when I upload with browser it's the same
