### ISSUE TITLE
Question error code

### ISSUE THREAD

**Issue by ManuCart** [3846masa/upload-gphotos#227]
Hi,

What is the error code when ````upload-gphotos```` encounture error to upload with lan, google api or everthing else.
I try this, but don't know if it's working
````
if ! upload-gphotos -u "$Username" -p "$Password" -a "$Album ($Year)" `ls`; then
       echo "ERROR"; return; fi
````

**Comment by 3846masa** [comment]
Exit code caused by argument error is 255.
https://github.com/3846masa/upload-gphotos/blob/64c30d7cc68a165340a775ff00d77295e49e576f/src/cli.js#L42

Exit code caused by other error is 3.
https://github.com/3846masa/upload-gphotos/blob/64c30d7cc68a165340a775ff00d77295e49e576f/src/cli.js#L76

Example.
```bash
find ./ -maxdepth 1 -type f | xargs upload-gphotos -u "$Username" -p "$Password" -a "$Album ($Year)"
if [ $? -ne 0 ]; then
  echo "ERROR";
fi
```

**Comment by ManuCart** [comment]
Ok, thank you for your help.
I need to try this
