### ISSUE TITLE
Failed to fetch the list of photos

### ISSUE THREAD

**Issue by ManuCart** [3846masa/upload-gphotos#234]
Hi,

With some album, I'm completely blocked
Impossible to create album name even try again
I try to change the album name but no way
It's appears after a lot of upload photos

````
ERROR Album "blah blah (2017)" is not found.
ERROR TypeError: Cannot read property 'map' of null
    at /usr/local/lib/node_modules/upload-gphotos/lib/index.js:397:35
    at Generator.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/upload-gphotos/node_modules/co/index.js:65:19)
Aborted
````

**Comment by 3846masa** [comment]
`Cannot read property 'map' of null` caused [here](https://github.com/3846masa/upload-gphotos/blob/v1.4.4/src/index.js#L298).
So, you failed to fetch the list of photos.

I have no idea why fail to fetch list. It is always success on my accounts.

**Comment by ManuCart** [comment]
I think I found the cause.
I uploaded an album with photos and after that I delete album name and photos on Google photos
I try to reupload album name and photos and I have this error.

**Comment by ManuCart** [comment]
The only way I found is to create album name on google photo and after that upload photos

**Comment by ManuCart** [comment]
After more tests, it's seem a bug because I don't know why but after delete album and upload same album  it's impossible to proceed

**Comment by ManuCart** [comment]
I try to understand your nodejs code and I have a question
What is exactly the code 74806772?

**Comment by 3846masa** [comment]
Sorry for late reply.
`74806772` is Google Photos' request code, I have no tips for it yet.
I searched request code reading a real request / response via browser.
