### ISSUE TITLE
Upload to shared album problem

### ISSUE THREAD

**Issue by leovicio** [3846masa/upload-gphotos#242]
Add photo to shared album does not return photo id

**Comment by leovicio** [comment]
The query changed has to send the key of the album together and have to adapt the code because the result is a bit different

**Comment by leovicio** [comment]
I modified what was already installed here if somebody can update the source

Album.js

class GPhotosAlbum {
  /**
   * @ignore
   */
  constructor({
    id, title, key, period = { from: new Date(0), to: new Date(0) },
    items_count = 0, _gphotos
  }) {
    /** @type {String} */
    this.id = id;
    /** @type {String} */
    this.title = title;
	this.key = key;
    /**
     * @type {Object}
     * @property {Date} from
     * @property {Date} to
     */
    this.period = period;
    /** @type {number} */
    this.items_count = items_count;
    /** @type {String} */
    this.type = 'album';

    Object.defineProperties(this, {
      '_gphotos': {
        value: _gphotos
      },
      '_logger': {
        value: _gphotos._logger
      }
    });
  }

----------------
 addPhoto(photo) {
    var _this = this;

    return (0, _co.wrap)(function* () {
      var _ref = yield _this.addPhotos([photo]),
          _ref2 = _slicedToArray(_ref, 1);

		  
	if(_ref2[0].length>10){
	var insefotoid = _ref2[0];
	}else {
	 var insefotoid = _ref2[0][0];
	}
	
	 const insertedPhotoId = insefotoid;
	
      return insertedPhotoId;
    })();
  }

-------------------

 addPhotos(photos) {
    var _this2 = this;
	
    return (0, _co.wrap)(function* () {
      const query = [photos.map(function (p) {
        return p.id;
      }), _this2.id];

      const results = yield _this2._gphotos._sendMutateQuery(79956622, query).catch(function () {
        // Fallback: If album is shared, use 99484733.
        const query = [[_this2.id], [2, null, [[photos.map(function (p) {
          return p.id;
        })]], null, null, [], []],_this2.key,[null,null,null,null,[null,[]]]];
        return _this2._gphotos._sendMutateQuery(99484733, query);
      }).catch(function (_err) {
        _this2._logger.error(`Failed to add photo in album. ${_err.message}`);
        return Promise.reject(_err);
      });

      const insertedPhotoIds = results[1] || [];
	  
      return insertedPhotoIds;
    })();
  }

**Comment by 3846masa** [comment]
Thanks for your report.
It's a good code.
Please create PR, I'll review and merge.

**Comment by leovicio** [comment]
I do not know how to do it
Lacking

index.js

const albumList = results[0].map(function (al) {
        const info = al.pop()['72930366'];
        return new _Album2.default({
          id: al.shift(),
          title: info[1],
          key: info[5],
          period: {
            from: new Date(info[2][0]),
            to: new Date(info[2][1])
          },
          items_count: info[3],
          _gphotos: _this6._gphotos
        });
      });

**Comment by leovicio** [comment]
I created the PR I do not know if I did it correctly I'm not familiar with it

**Comment by leovicio** [comment]
CLi Exemple

```
#!/usr/bin/env node
import fs from 'fs-promise';
import log4js from 'log4js';
import argParser from 'yargs';
import read from './utils/read';
import GPhotos from './index';

log4js.configure({
  appenders: {
    console: {
      type: 'console',
      layout: {
        type: 'pattern',
        pattern: '%[%p%] %m'
      },
    },
  },
  categories: {
    default: {
      appenders: ['console'],
      level: 'all'
    }
  }
});
const logger = log4js.getLogger();

argParser.demand(1);
argParser.usage(`Usage: upload-gphotos file [...] [-u username] [-p password] [-a albumname]`);
argParser.options('u', {
  alias: 'username',
  desc: 'Google account username.'
});
argParser.options('p', {
  alias: 'password',
  desc: 'Google account password.'
});
argParser.options('a', {
  alias: 'album',
  array: true,
  desc: 'Album where uploaded files put.'
});
argParser.help('h').alias('h', 'help');

const { u: username, p: password, _: files, a: albumNameList } = argParser.argv;

(async () => {
  await Promise.all(files.map((path) => fs.access(path)))
    .catch(() => {
      argParser.showHelp();
      process.exit(255);
    });

  const gphotos = new GPhotos({
    username: username || (await read({ prompt: 'Username: ' })),
    password: password || (await read({ prompt: 'Password: ', silent: true })),
    options: {
      progressbar: true,
      logger: logger
    }
  });
  await gphotos.login();

  const albumList = [];
  const photos = [];
  const photosup = [];
  const shareAlbumList = [];
  
  for (let path of files) {
    const photo = await gphotos.upload(path);
	
    if (albumNameList && albumList.length !== albumNameList.length) {
      for (let albumName of albumNameList) {
        const album = await gphotos.searchOrCreateAlbum(albumName);
        albumList.push(album);
      }
    }

    for (let album of albumList) {
    const  photoalbum = await album.addPhoto(photo);
	 if (album.key == null) {
		 const sharealbum = await gphotos.shareAlbum(album.id);
		 shareAlbumList.push(sharealbum);
	 }
	 photos.push({id:photoalbum});
    }
    
	photosup.push(photo);
	
  }

  console.info('Album');
  console.info(JSON.stringify(albumList, null, 2));
  
  console.info('Share Album Info');
  console.info(JSON.stringify(shareAlbumList, null, 2));
  
  console.info('Photo');
  console.info(JSON.stringify(photosup, null, 2));
  console.info('Photo in Album');
  console.info(JSON.stringify(photos, null, 2));
  
})().catch(function (err) {
  logger.error(err.stack);
  process.abort();
});
```

**Comment by monster1777** [comment]
any update?

**Comment by 3846masa** [comment]
upload-gphotos already supported to adding photos to shared album.
