### ISSUE TITLE
Can't work with proxy.

### ISSUE THREAD

**Issue by kenturkj** [3846masa/upload-gphotos#262]
Seem code doesn't wok with proxy.  When I use code in my PC, it work great. But when I connect my PC with VPN or proxy, it can't upload.
Can't fetch GPhotos params

Hope you can check it. Thank you very much!

**Comment by 3846masa** [comment]
Sorry for late response.

I think, you should login via browser first when connecting via VPN or proxy.
Google maybe record latest IP address when logged in with normal browser, and check IP address if matched with previous IP address.

**Comment by kenturkj** [comment]
Thanks :)
