### ISSUE TITLE
Error is the following: sendMutateQuery

### ISSUE THREAD

**Issue by marcus645** [3846masa/upload-gphotos#263]
Failed to add photo to album. Cannot read property 'sendMutateQuery' of undefined[31mERROR[39m TypeError: Cannot read property 'sendMutateQuery' of undefined at GPhotosAlbum. (/usr/lib/node_modules/upload-gphotos/lib/Album.js:33:47) at next (native) at /usr/lib/node_modules/upload-gphotos/lib/Album.js:7:71 at __awaiter (/usr/lib/node_modules/upload-gphotos/lib/Album.js:3:12) at GPhotosAlbum.addPhotos (/usr/lib/node_modules/upload-gphotos/lib/Album.js:31:16) at GPhotosAlbum. (/usr/lib/node_modules/upload-gphotos/lib/Album.js:26:50) at next (native) at /usr/lib/node_modules/upload-gphotos/lib/Album.js:7:71 at __awaiter (/usr/lib/node_modules/upload-gphotos/lib/Album.js:3:12) at GPhotosAlbum.addPhoto (/usr/lib/node_modules/upload-gphotos/lib/Album.js:25:16)

UPLOAD works, but not adding to album...

**Comment by 3846masa** [comment]
Thanks for report. I'll fix.

**Comment by 3846masa** [comment]
Fixed at v2.0.2
