### ISSUE TITLE
remote upoald to google photos

### ISSUE THREAD

**Issue by Abdel-ilah** [3846masa/upload-gphotos#265]
Hello friends 
i'm not developer and i don't know how i use your app but it's look like interesting, and i think that's have a rapport with my question..., i need something for upload my .gpj .mp4 .avi files by Remote upload from other servers to my google photo account,
before i use a website but it does not work anymore.

Thank you

**Comment by marcus645** [comment]
It's working **totally fine** ( it has some bugs that it sometimes stops, but all in all it's fine). So read the instructions, and try again.
Regards.

**Comment by 3846masa** [comment]
Please try to login via browser on remote server first.
See https://github.com/3846masa/upload-gphotos/issues/113#issuecomment-277141489

**Comment by anhthoai** [comment]
We can use this https://save.thoaimedia.com/ without installing anything

**Comment by marcus645** [comment]
@anhthoai: 
That is a payed thing and has nothing to do with this script, please don't spam your crappy links. Thanks.
