### ISSUE TITLE
NPM install doesnt work

### ISSUE THREAD

**Issue by mkoivuporras** [3846masa/upload-gphotos#266]
I get following error message while trying to use npm install on Raspberry Pi

'3846masa/axios-cookiejar-support' in not in the npm registry. You should bug the author to publish it. It was specified as a dependency of 'upload-photos'

**Comment by ManuCart** [comment]
Please use code beside for installation on raspberry pi
````sudo npm install -g upload-gphotos````

**Comment by mkoivuporras** [comment]
pi@pi-booth:~ $ sudo npm install -g upload-gphotos
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 '3846masa/axios-cookiejar-support' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'upload-gphotos'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.41-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "upload-gphotos"
npm ERR! cwd /home/pi
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

**Comment by 3846masa** [comment]
`@3846masa/axios-cookiejar-support` is already published.
https://www.npmjs.com/package/@3846masa/axios-cookiejar-support

I think your npm's version is too lower. Please try `npm i -g npm` first.

**Comment by 3846masa** [comment]
FYI: https://docs.npmjs.com/getting-started/scoped-packages
> **You need a version of npm greater than 2.7.0**, and you'll need to log in to npm again on the command line if this is your first time using scoped modules.

**Comment by ManuCart** [comment]
Working with code below on Raspberry Pi
````
wget https://nodejs.org/dist/v8.3.0/node-v8.3.0-linux-armv6l.tar.gz
sudo tar -xvf node-v8.3.0-linux-armv6l.tar.gz --strip 1 -C /usr/local
rm node-v8.3.0-linux-armv6l.tar.gz
````

**Comment by 3846masa** [comment]
Closed. (If you have this issue yet, please write comment.)
