### ISSUE TITLE
Cannot delete photos(?)

### ISSUE THREAD

**Issue by ParadisusParadoxum0000** [3846masa/upload-gphotos#275]
Hello!

First of all thank you so much for creating this library, it really made a lot of things possible for me and I'm very grateful! 

I've used this library to upload images onto gphotos successfully but I've run into a problem with deleting them and I'm not sure why, my code for deleting the photos looks like this:

```
/*new GPhotos and login done beforehand*/

var deleteImagesByIds = function(imageIds){
	console.log(imageIds);
	for(var i = 0; i < imageIds.length; i++){
		gphotos.fetchPhotoById(imageIds[i])
		.then(function(photo){
			console.log("removing photo");
			console.log(photo); //this logs info of the image so it looks like the fetch is successful
			photo.remove()
			.then(function(result){
				console.log(result); //this logs true but on my gphotos account I can still see the image
			})
			.catch(function(err){
				console.log("failed to remove photo: " + err);
			});
		})
		.catch(function(err){
			console.log("failed to fetch photo to remove: " + err);
		});
	}
}
```

Can you please help me figure out why it isn't deleting?

One more question, I'm currently storing the imageIds into the database so I can delete them later with the above code, is there a way to fetch the images by name(which are currently all named in a specific format like "profileImage{SomeUserName}.jpeg") instead of imageId?

Thank you for taking your time reading this and I wish you a great 2018!

**Comment by 3846masa** [comment]
Hi @ParadisusParadoxum0000 
I ran your code on my environment, but it works.
I have no idea why you cannot remove photo, sorry.
Please tell me more details of your photo (filetype, size, etc.).

By the way, this library cannot search by filename or other parameters.
I have no plan to implement search methods now.

**Comment by ParadisusParadoxum0000** [comment]
Hi again, after some more testing I figured out what the issue was, if the image was added to an album(which I do for the uploaded images), photo.remove() won't delete them from gphotos. Can this be fixed or is there a way to programmatically remove the image from the album first before I call photo.remove()?

Also can you please tell me what album.fetchPhotoList and album.fetchAllPhotoList do? Thanks in advance!

**Comment by 3846masa** [comment]
I checked. `photo.remove();` cannot work when photo is in album.
I'll fix it, but it will take a while to fix it because Google Photos API was renewed (Ref. #280).

**Comment by 3846masa** [comment]
**P.S.**
`album.fetchAllPhotoList` returns all photos in album.
`album.fetchPhotoList` returns some photos in album and next cursor.
Normally, you use `fetchAllPhotoList`.
You want more details, please read code.

**Comment by 3846masa** [comment]
I'll close this issue.
If you have issues yet, please reopen or create new issue.
