### ISSUE TITLE
Upload-gphotos as nodejs module

### ISSUE THREAD

**Issue by Laurens0619** [3846masa/upload-gphotos#277]
Hi,

I am trying to use the upload-gphotos as a module but not succeeding:
(node:1390) UnhandledPromiseRejectionWarning: TypeError: GPhotos is not a constructor

I installed the module via npm and try to call it like:
const GPhotos = require('upload-gphotos').GPhotos;
const gphotos = new GPhotos({ username:.......

Any clue?

**Comment by 3846masa** [comment]
index.ts use default export.
Please try `const GPhotos = require('upload-gphotos').default;`

**Comment by Laurens0619** [comment]
This works! thanks :)
