### ISSUE TITLE
searchOrCreateAlbum doesn't create an album

### ISSUE THREAD

**Issue by Nibbler999** [3846masa/upload-gphotos#278]
It just throws an error if the album does not exist. Looks like it was broken in the TypeScript conversion.

**Comment by 3846masa** [comment]
Please paste error message.

**Comment by Nibbler999** [comment]
Error: Album "TestAlbum" is not found.

**Comment by 3846masa** [comment]
Ok, I see. I'll fix it.

**Comment by 3846masa** [comment]
Fixed at #279 and will be released as v2.0.7 soon.

**Comment by 3846masa** [comment]
Released as v2.0.7

**Comment by Nibbler999** [comment]
Fix confirmed, thanks.
