### ISSUE TITLE
REQUEST_REJECTED after first time successfully upload

### ISSUE THREAD

**Issue by cnritng** [3846masa/upload-gphotos#283]
Fail too on chrome latest version,error info as below:
{"errorMessage":{"reason":"REQUEST_REJECTED","additionalInfo":{"uploader_service.GoogleRupioAdditionalInfo":{"completionInfo":{"status":"REJECTED","customerSpecificInfo":{"statusCode":67}},"requestRejectedInfo":{"reasonDescription":"agent_rejected"}}},"upload_id":"AEnB2UrHl3GpkaK8kHXxSzqg_dgyqdeDvQZUFFR6wGdQ7GeY1FYVzLJVlwYC29J6GecRJKUie4wSgzh52vUd-s5QB-Vwk*****"}}

PS:
file type:video(mkv)
file size:about 1GB

**Comment by 3846masa** [comment]
Thanks your report.
If you cannot upload file via Google Photos website, that file cannot be supported by this library because of Google Photos' specification.

It is related to # 256, please write there.
