### ISSUE TITLE
ERROR: Can't access Google photos

### ISSUE THREAD

**Issue by Guilty-King** [3846masa/upload-gphotos#286]
Hey guys , 
Is the binary still working ?
I am getting the following error even tho I have enabled less secure apps on my Google account 
Hope you can help

ubuntu@coffee-sage:~/seed$ ./upload-gphotos-linux 202688.jpg -u myname@gmail.com -p qwerty132 -a Kakegurui
ERROR Failed to login. Can't access to Google Photos
{ version: 'tough-cookie@2.3.3',
  storeType: 'MemoryCookieStore',
  rejectPublicSuffixes: true,
  cookies:
   [ { key: 'NID',
       value: '122=Cct7o3JAl_AtaSfLeaqWQfVmT8hCwRMWsegonPAxfH1o_9mVRtkxcNiGDBxT7zv-jsL4tPgXOsrmMQ1wVRTB0sC85OvmRoFuYmTURvP1dBttYgSGBE0BxG4AWmVPA8s3',
       expires: '2018-08-04T09:02:34.000Z',
       domain: 'google.com',
       path: '/',
       httpOnly: true,
       hostOnly: false,
       creation: '2018-02-02T09:02:34.740Z',
       lastAccessed: '2018-02-02T09:02:35.819Z' },
     { key: 'GAPS',
       value: '1:RaAOTuO73ii_7ONlBA2fBi6buuBi-A:2eJIkayQhhl96Mbx',
       expires: '2020-02-02T09:02:34.000Z',
       domain: 'accounts.google.com',
       path: '/',
       secure: true,
       httpOnly: true,
       extensions: [Object],
       hostOnly: true,
       creation: '2018-02-02T09:02:34.807Z',
       lastAccessed: '2018-02-02T09:02:34.862Z' } ] }
ERROR Error: Can't access to Google Photos
    at GPhotos.<anonymous> (/snapshot/project/lib/index.js:162:39)
    at next (native)
    at fulfilled (/snapshot/project/lib/index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 1: node::Abort() [./upload-gphotos-linux]
 2: 0x1076fd9 [./upload-gphotos-linux]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [./upload-gphotos-linux]
 4: 0x9c51ee [./upload-gphotos-linux]
 5: 0x9c5a8e [./upload-gphotos-linux]
 6: 0x170e5aa092a7
Aborted (core dumped)
ubuntu@coffee-sage:~/seed$

**Comment by Laurens0619** [comment]
I am having the error since a few days: Can't access to Google Photos

**Comment by 3846masa** [comment]
Please try to use latest (v2.0.8) binary.

**Comment by Guilty-King** [comment]
I tired latest 2.0.8 release and it worked once when logged in my account the first time 
But now after restart I am able to upload using xrdp (browser) session but not able to use cli , gives the same error

**Comment by Guilty-King** [comment]
Thank you for your help 
I got a single line output after running above code in node v6.11.4
```
ubuntu@coffee-sage:~/seed/gphotos$ node gphotos.js
200 undefined
```
I also tried uploading a pic with your binary release and it worked 

My conclusion is Google temporarily blocks ip if you try directly uploading photos before logging in using GUI

**Comment by Guilty-King** [comment]
Just a few mins later 
I tried to do the same for my other Google dummy account 
Open browser (already logged in)
Open photos.google.com
Run the nodejs code given above 
And I got this error 
```
ubuntu@coffee-sage:~/seed/gphotos$ node gphotos.js
(node:4262) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Failed to login
```

Not sure what's the condition for it working 
Also I get a security alert for my working account but not for this one

**Comment by 3846masa** [comment]
Thanks for your report.
Let me confirm one thing: Have you already been turned on "Allowing less secure apps to access your account"?

**Comment by Guilty-King** [comment]
Yes ,I got the mail regarding it 
Also I was thinking if the problem is with getting a cookie by using less secure login then you also provide option to feed cookie instead of username and password 
Ref. https://medium.com/@silverstag/google-drive-to-google-photos-direct-transfer-using-redhat-openshift-733259eab284

**Comment by 3846masa** [comment]
@kparks29 
I can't know why that error causes. I can't fix it, sorry.
(It works in my environments, on Windows / macOS / Ubuntu etc.)

- Try with another account.
- Try another photo which is small size.
- Use official API (c.f. https://developers.google.com/photos/library/guides/overview)
  - BTW, upload-gphotos don't support official API (see #304)
