### ISSUE TITLE
Can't run code

### ISSUE THREAD

**Issue by ehevnn** [3846masa/upload-gphotos#289]
Hello,
When install node & npm upload-gphotos, run "upload-gphotos file [path_to_my_file.png] -u MYUSERNAME -p MYPASSWORD" I have the following error 👎 

> 1: node::Abort() [node]
>  2: 0x8cae29 [node]
>  3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
>  4: 0xae0b7c [node]
>  5: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
>  6: 0x11e39b7842fd
> Aborted (core dumped)

Anyone can help me?

Thanks you!

**Comment by 3846masa** [comment]
Please try `upload-gphotos path_to_my_file.png -u MYUSERNAME -p MYPASSWORD`.
