### ISSUE TITLE
Using ID to direct access files 

### ISSUE THREAD

**Issue by Guilty-King** [3846masa/upload-gphotos#300]
I been uploading a few mkv mp4 video clips from my DSLR and got normal output like 
```
Uploading [============================] 100% 0.0s

[
  {
    "type": "video",
    "id": "AF1QipMyEDLa89r6cPTPUv1bMh9ir1d7g5KAR4eEXmTM",
    "uploadedAt": "2018-04-29T07:36:41.617Z",
    "createdAt": "2018-04-29T07:36:40.821Z",
    "title": "DCS-001-20180429.mkv",
    "description": "",
    "rawUrl": "https://lh3.googleusercontent.com/-04Y1KpcwTxI/WuV2CDiKZeI/AAAAAAAAEx8/hF5-aTtt_qY6OTomI3to88EejUCdbYZiwCLcBGAs/DCS-001-20180429.mkv"
  }
]
 
```

The above data is modified but could I get direct link to source it in my html page (creating a photo gallery) as the rawUrl isn't a video but just the video thumbnail
I have seen links like redirector.googleusercontent.com/blah blah but couldn't find how to get it 

Any help appreciated

**Comment by 3846masa** [comment]
rawUrl is Google Photos API's Base URL.
See https://developers.google.com/photos/library/guides/access-media-items#base-urls
