### ISSUE TITLE
Use Official Google Photos API

### ISSUE THREAD

**Issue by neocryptek** [3846masa/upload-gphotos#304]
New Photos API finally announced!

https://developers.google.com/photos/library/reference/

It's still in preview so somewhat limited, but should be great once fully baked.

**Comment by 3846masa** [comment]
Thanks for reporting!
I'll rewrite with new Google Photos API.

**Comment by 3846masa** [comment]
https://developers.google.com/photos/library/guides/api-limits-quotas

> All media items uploaded to Google Photos using the API are stored in full resolution at original quality. They count toward the user’s storage.

Oops. I want to upload photos as high quality mode (not count toward storage).
I decide not to use this API at present, sorry.

**Comment by neocryptek** [comment]
Yeah, like I said above it's limited right now since it's still in preview:

> Note: The Google Photos Library API is currently in developer preview. These limits are set low to enable you to try out the API and its features. The limits aren't for production launch, and will be increased once the API enters general availability.

**Comment by 3846masa** [comment]
I see.
However, Preview API is not necessary for me, so I have no plan to develop with preview API.

**Comment by ManuCart** [comment]
Hi,
Please would you like to reconsider your choice and using official google photo API
I think you can use the high quality mode just by uploading photos less than 16 megapixels.
Just testing photo weight and resize it before uploading.
Need help because your script not working for me anymore.

**Comment by 3846masa** [comment]
I tried upload 400 images (which size is 651 x 1024 pixels, it's less than 16MP) with "Original quality" option.

<details>
<summary><b>BEFORE</b></summary>

![](https://user-images.githubusercontent.com/5629366/47612073-592fad80-dab6-11e8-88f6-05aecf4ae09e.PNG)

</details>

<details>
<summary><b>AFTER</b></summary>

![](https://user-images.githubusercontent.com/5629366/47612085-95fba480-dab6-11e8-8e32-f75aae9258ee.PNG)

</details>

(Screenshot is Japanese.) It reduce Google Drive quota by 0.04GB.

I would like to use Google Drive quota via "High quality" option.
So, I have no plan to use Google Photos API.

If you want to use Google Photos API, please consider other cli tools.

<details>
<summary><b>LIST OF OTHER TOOLS USING OFFICIAL API</b></summary>

- [nmrshll/gphotos-uploader-cli: Command line tool to mass upload media folders to your google photos account(s) (Mac OS / Linux)](https://github.com/nmrshll/gphotos-uploader-cli)
- [mholt/photobak: Back up your content from Google Photos](https://github.com/mholt/photobak)
- [int128/gpup: A command to upload photos and movies to Google Photos Library](https://github.com/int128/gpup)
- [eshmu/gphotos-upload: Simple but flexible script to upload photos to Google Photos and add to a particular album. Useful if you have photos in a directory structure that you want to reflect as Google Photos albums.](https://github.com/eshmu/gphotos-upload)


</details>

**Comment by ManuCart** [comment]
Hi Masahiro,
Thank you very well for looking for.
I would like use "High quality" option too.
My only solution is to use flickr by it's with lower options.
Thanks again

**Comment by adrianlzt** [comment]
I have seen that it is possible to upload photos with "Original Quality" and then use the [Recover storage](https://productforums.google.com/forum/#!msg/photos/IMZ-2I66kLo/mgO8A4f_BwAJ) (https://photos.google.com/settings) to convert them
