### ISSUE TITLE
動画をアップロードした場合の日付

### ISSUE THREAD

**Issue by hagithu** [3846masa/upload-gphotos#306]
upload-gphotosで動画をアップした場合、createdAtがアップロードした日付になってしまうのですが、ファイルの更新日付をcreatedAtにすることはできないでしょうか？
ブラウザよりGoogle Photoを開いて、ドラッグ&ドロップでアップロードした場合は、createdAtがファイルの更新日付でアップされております。
できれば、更新日付で動画を管理したい次第です。

**Comment by 3846masa** [comment]
Google Photos の仕様を把握してるわけではないので、正確なことは言えませんが、アップロード直後にはまだ `createdAt` は解析されてない状態です
少し時間をおいてから、 `GPhotosPhoto#fetchInfo` で再度情報を取得してみてください

https://3846masa.github.io/upload-gphotos/classes/_photo_.gphotosphoto.html#fetchinfo
