### ISSUE TITLE
Failed to create album. Bad Request.

### ISSUE THREAD

**Issue by rude78** [3846masa/upload-gphotos#313]
I used your library to upload >10.000 photos. Suddenly uploading failed with 
Uploading [=======================================================================================] 100% 0.0s

ERROR Failed to create album. Bad Request
ERROR Error: Bad Request
    at GPhotos.<anonymous> (C:\snapshot\project\lib\index.js:113:39)
    at next (native)
    at fulfilled (C:\snapshot\project\lib\index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Any Ideas?

**Comment by 3846masa** [comment]
Thanks for reporting.
Google Photos changed internal API recently.
I'll rewrite but it takes long time for fixing.

Related to https://github.com/3846masa/upload-gphotos/issues/280.

**Comment by 3846masa** [comment]
@rude78 
I released v2.0.12 for fixing issue, please try it.

**Comment by rude78** [comment]
Thx. This solved the issue.
