### ISSUE TITLE
Error when uploading multiple images or folder

### ISSUE THREAD

**Issue by shindycham01** [3846masa/upload-gphotos#317]
When I try to upload a folder with multiple images i get the following error message:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)

When uploading the files one by one they upload just fine.

**Comment by 3846masa** [comment]
Please write more details for helping.

- What command you typed? or What code you write?
- Filetype (jpg, mp4 etc.)
- Filesize

**Comment by shindycham01** [comment]
What command you typed?

upload-gphotos /home/user/fotos/ -u "username@gmail.com" -p "password"

Filetype?

The folder contains 114 images with the Filetype .jpg

The folder is 79,5 MB big. Each image-size ranges around 500 KB up to 1 MB.

I've tried to minimize the amount of images in the folder to 2 images and still the error occurs.

**Comment by 3846masa** [comment]
upload-gphotos command cannot receive directory as arguments.

Please try `upload-gphotos /home/user/photos/*.jpg -u username@gmail.com -p PASSWORD`

**Comment by shindycham01** [comment]
This works as a workaround. Thank you for your help.
