### ISSUE TITLE
Login Issue + Solution/Feature Request

### ISSUE THREAD

**Issue by vovler** [3846masa/upload-gphotos#322]
Fighting against Google login is an annoying uphill battle. For example, now it's not working (at least for me). 

I see the application already stores login cookies after the first login. The only thing left is to let the user import his own cookies via a JSON file. This would also bypass captcha/sms verification issues.

You would then have these two authentication methods:

`upload-gphotos photo1.jpg -u example@example.com -p password`
`upload-gphotos photo1.jpg --cookies account1.json`

Let me know what you think :)

**Comment by ManuCart** [comment]
not important to me but I prefer the second one
do the simple for you

**Comment by vovler** [comment]
@ManuCart I understand, but I can't login for some reason, and other users too #321 . 
That's why I suggested a simple fix/workaround that will save @3846masa a lot of headache from users that can't login for some reason and if/when google updates the login page again.

**Comment by 3846masa** [comment]
Login issue is #321. Please discuss in #321.

Also, I have no plan to support cookie file via CLI, because you can write code for passing cookiejar.

e.g.
```js
const jar = tough.CookieJar.deserializeSync(cookieJSON);
const gphotos = new GPhotos({
  username: null,
  password: null,
  options: {
    jar: jar,
  },
});
// ...
```
