### ISSUE TITLE
I was getting the "Can't access to google photos" error, but I fixed it

### ISSUE THREAD

**Issue by Taiiwo** [3846masa/upload-gphotos#325]
I was getting the "Can't access to google photos" error because I was being redirected from `photos.google.com` to `google.com/photos/about` as though I wasn't signed in. I tried a bunch of stuff trying to get google to recognise the IP, signed in over a VPN, made a login script using selenium.

TL;DR: I injected my cookies from my browser to line 47 of index.js in /usr/lib/node_modules/upload_gphotos/lib/index.js to look like this:
```diff
        this.axios = axios_cookiejar_support_1.default(axios_1.default.create({
            headers: {
                'User-Agent': `Mozilla/5.0 UploadGPhotos/${packageInfo.version}`,
+                'Cookie':'NID=really long cookie string filled with sensitive information-----
            },
            validateStatus: () => true,
            maxRedirects: 0,
            jar: this.options.jar,
            withCredentials: true,
            responseType: 'text',
            transformResponse: [data => data],
        }));
```
I hope this information helps to update the library and make it more robust. Great work. I uploaded an 8GB "file" without using up my allowance!

**Comment by Taiiwo** [comment]
It was working for a while, but now I'm getting this message:

```
ERROR Failed to upload. Retry after 3 sec. Server Error: sessionStatus is not found.
ERROR Failed to upload. Retry after 3 sec. Server Error: sessionStatus is not found.
ERROR Failed to upload. Server Error: sessionStatus is not found.
ERROR Error: Server Error: sessionStatus is not found.
    at GPhotos.<anonymous> (/usr/lib/node_modules/upload-gphotos/lib/index.js:328:39)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/upload-gphotos/lib/index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 1: 0x8dbaa0 node::Abort() [node]
 2: 0x96e489  [node]
 3: 0xb60aff  [node]
 4: 0xb61669 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 5: 0x27e8309dbe1d
return code: -6
```

I've tried updating my cookie but that doesn't seem to fix it. It it possible that I've been shadow banned. My cookie looks like it's changed formats. I can still upload images from the website though....

**Comment by ManuCart** [comment]
Hope you find a solution, I'm waiting too. Good luck !

**Comment by Taiiwo** [comment]
Looks like my access came back. I don't even know if refreshing my cookie did anything. Looks like I was temp banned? Nothing I uploaded was removed, there's no sign anything happened.

I'll keep this thread updated with how it goes, but I hope the script changes to incorporate a working method of getting a working cookie from the username and password.

**Comment by 3846masa** [comment]
If you want to cookie string directly, please use `jar` option.

```js
const jar = tough.CookieJar.deserializeSync(cookieJSON);
const gphotos = new GPhotos({
  username: null,
  password: null,
  options: {
    jar: jar,
  },
});
await gphotos.login();
```

Login issue is #322. Please discuss in #322.
