### ISSUE TITLE
Not working - help needed...

### ISSUE THREAD

**Issue by JBlyth** [3846masa/upload-gphotos#326]
What is going wrong here. Any help much appreciated. What do I need to do to get the image to upload please - sorry if I am missing something obvious...

I am getting an error with:-
upload-gphotos C:\Users\XXX\Downloads\Temp\Test11.jpg --quiet -u XXXX@gmail.com -p XXXX -a Test

Return Code:-
{ version: 'tough-cookie@2.5.0',
  storeType: 'MemoryCookieStore',
  rejectPublicSuffixes: true,
  cookies:
   [ { key: 'NID',
       value:
        '154=HcO6yS1oDVYi_y_RR9zDhrBvyKnw5ggzw6uiPWGC7Xl4C_WobmlcF5igH8kJjHyai1ataZC059SREgnxiP-gw1cQfALc5UAYOoD7WE1sSQpcZ3FEIiKxiwz7OFLs_BGhyhXXycy9rxY_Oz4KxUuiKFhbPnPNEyhtiUNF-z3z6cg',
       expires: '2019-07-05T15:42:28.000Z',
       domain: 'google.com',
       path: '/',
       httpOnly: true,
       hostOnly: false,
       creation: '2019-01-03T15:42:26.937Z',
       lastAccessed: '2019-01-03T15:42:29.633Z' },
     { key: 'GAPS',
       value: '1:zeTVePXHaf2GZbICIFL2AfRlEzUKLw:PpZXFQekWFV2_wGj',
       expires: '2021-01-02T15:42:30.000Z',
       domain: 'accounts.google.com',
       path: '/',
       secure: true,
       httpOnly: true,
       extensions: [Array],
       hostOnly: true,
       creation: '2019-01...

**Comment by Taiiwo** [comment]
Did you see this: https://github.com/3846masa/upload-gphotos/issues/325

**Comment by JBlyth** [comment]
Thank you Taiiwo,

I shall wait for a fix to be found. Good Luck!

Cheers John 
in Sunny Carnarvon - Western Australia

**Comment by 3846masa** [comment]
See #321

**Comment by JBlyth** [comment]
Thank you Miyashiro-san,

The new version works very well.

I am very lucky to spend 2 months each year in Takikawa, Hokkaido. I have
towed gliders at Takikawa Sky Park for the last 21 years, but sadly my
Japanese language skill is still very bad! http://www.takikawaskypark.jp/

With very best wishes,
John - from Sunny Carnarvon, Western Australia.
