### ISSUE TITLE
Update Google Photos API on browser

### ISSUE THREAD

**Issue by tsukasachandesu** [3846masa/upload-gphotos#334]
The old API has upload limitation and I can not upload over 10GB per day.
I have no problems uploading via the web interface.
Google Photos on browser is using new API ( `https://photos.google.com/_/upload/uploadmedia/interactive?authuser=1` ) now.
So, rewrite to use new  API.
#331

**Comment by tsukasachandesu** [comment]
#331

**Comment by tsukasachandesu** [comment]
REQUEST_REJECTEDになってからも小さい画像などはアップロードできるのですが、大きい動画はアップロードできません。ブラウザからはアップロードできます。

**Comment by 3846masa** [comment]
Released as v3.0.5.
