### ISSUE TITLE
Error creating album

### ISSUE THREAD

**Issue by jbajada** [3846masa/upload-gphotos#452]
Trying to upload a single image and create a new album (no photos or albums exist - its a new gmail account). But getting the following error:

TypeError: Cannot read property 'map' of null
    at GPhotos.fetchAlbumList (/usr/lib/node_modules/upload-gphotos/lib/GPhotos.js:34:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
1: 0x8fa050 node::Abort() [node]
2: 0x98c4f9  [node]
3: 0xb8e64f  [node]
4: 0xb8f1b9 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
5: 0x18df27f5be1d
Aborted
upload-gphotos ./test.jpg -u xxxx@gmail.com -p XXXXXXXXX --album "2020 - Test Album 1"

**Comment by 3846masa** [comment]
Thanks for reporting.
This error was fixed in v4.1.1.
Please try new version.
