### ISSUE TITLE
Error fetching photo list

### ISSUE THREAD

**Issue by ParadisusParadoxum0000** [3846masa/upload-gphotos#455]
Tried to fetch a list of all the photos in the account and in an album with fetchPhotoList:

```
const fs = require('fs');
const { GPhotos } = require('upload-gphotos');

const gphotos = new GPhotos();

(async () => {
  await gphotos.signin({username: 'someuser@mail.com', password: 'thankyouforthisamazinglibrarybtw'});

  const album = (await gphotos.searchAlbum({ title: 'Experimental' })) || (await gphotos.createAlbum({ title: 'Experimental' }));
  
  const photoList = await gphotos.fetchPhotoList();
  
  const albumPhotoList = await album.fetchPhotoList();
 
})().catch(console.error);
```

Getting the following errors:

TypeError: Cannot destructure property 'cursor' of 'undefined' as it is undefined.
    at GPhotos.fetchPhotoList (C:\Users\U\Desktop\test\node_modules\upload-gphotos\lib\GPhotos.js:79:28)

TypeError: Cannot destructure property 'cursor' of 'undefined' as it is undefined.
    at GPhotosAlbum.fetchPhotoList (C:\Users\U\Desktop\test\node_modules\upload-gphotos\lib\GPhotosAlbum.js:52:28)

**Comment by 3846masa** [comment]
v4.0.0 has breaking changes for methods.
I have no plan to create document, so read code or use TypeScript for type checking.

---

NOTE
`gphotos.fetchPhotoList()` should be passed `cursor` params.
At first time, `cursor` should be null.

```ts
const list = [];
let cursor = null;
do {
  const { results, nextCursor } = await gphotos.fetchPhotoList({ cursor });
  list.push(...results);
  cursor = nextCursor;
} while (cursor !== null);
```

**Comment by ParadisusParadoxum0000** [comment]
Thank you for the help, I can successfully fetch items from the account and from albums now.
