### ISSUE TITLE
2 Step Verification - Application Specific passwords

### ISSUE THREAD

**Issue by Mattie432** [3846masa/upload-gphotos#66]
Do you know if this works with application passwords? 2-step-verification is enabled on my account so an application specific password is required but I seem to get "Failed to login..."

**Comment by 3846masa** [comment]
Sorry, this package is not supported application password.

First, this package will login like browser, not application.
Second, this package requires to turn on "Allowing less secure apps to access your account",
but you cannot do that when 2-step-verification is enabled.
See https://www.google.com/settings/security/lesssecureapps .

**Comment by Mattie432** [comment]
Understood, in that case it may not be too difficult to include the auth-code from 2-step verification? If the application is essentially passing parameters to a webpage?

**Comment by 3846masa** [comment]
This package use jsdom and request module, but Google system says "This is not secure browser.".
Maybe using electron, you can do with 2-step verification.
Electron is huge size and difficult to use on cli, so I have no plans to support that at this point in time.

**Comment by Mattie432** [comment]
No worries, might look into other possibilities if I have time & get back to you. Thanks.
