### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by NightFury135269** [3846masa/upload-gphotos#687]
Sorry this is not issue but cant find where to ask this. I dont know much about google auth. Can anyone please give me a full detailed info about how to login to upload-gphotos and upload a local folder to gphotos

**Comment by panoti** [comment]
@NightFury135269 Do you read ```https://github.com/3846masa/upload-gphotos/blob/master/example/index.js```? If you want upload all files in a folder, I think you should study about nodejs or typescript.
