### ISSUE TITLE
写真のタイトル

### ISSUE THREAD

**Issue by roto5296** [3846masa/upload-gphotos#74]
fetchAllPhotoListで得られる、Photoの中にはタイトルが含まれていませんが、タイトルを取得してくることは不可能なのでしょうか？

**Comment by 3846masa** [comment]
upload-gphotos は，Google Photos の通信を解析したものを元に，模倣してコードを書いています．
実際に解析すれば恐らく取得する手段があるとは思いますが，現時点で僕自身で実装する予定はありません．

**Comment by roto5296** [comment]
なるほど　通信を見ていたらタイトルが取得できそうだったので、実装してプルリク出します

**Comment by 3846masa** [comment]
@roto5296 PR マージしました，ありがとうございます！
v1.1.0 がリリースされ次第使えます

**Comment by 3846masa** [comment]
ドキュメントも更新されています．
https://doc.esdoc.org/github.com/3846masa/upload-gphotos/class/src/Photo.js~GPhotosPhoto.html
